project:
  type: book
  output-dir: docs

engine: knitr
filters:
  - webr

webr:
  cell-options:
    autorun: true

date: "last-modified"
date-format: iso
number-depth: 2
author: "David Dalpiaz, modified by Devan Becker"
execute:
    warning: false
    cache: true

book:
  title: "Applied Statistics with R"
  subtitle: "Forked from daviddalpiaz/appliedstats"
  author: "[David Dalpiaz](https://daviddalpiaz.org/), modified by Devan Becker"
  date: "last-modified"
  page-navigation: true
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - part: Background
      chapters:
        - 01_r-intro.qmd
        - 02_data-and-programming.qmd
        - 03_data-summary.qmd
        - 04_prob-and-stat.qmd
        - 05_r-resources.qmd
    - part: OLS Basics
      chapters:
        - 06_slr.qmd
        - 07_slr-inf.qmd
        - 08_mlr.qmd
    - part: Choosing Models
      chapters:
        - 09_model-building.qmd
        - 10_cat-int.qmd
        - 11_anova.qmd
        - 12_diagnostics.qmd
        - 13_transformations.qmd
        - 14_collinearity.qmd
        - 15_selection.qmd
    - part: Advanced Topics
      chapters:
        - 17_logistic.qmd
        - 18_beyond.qmd

format:
  html:
    theme:
      light: [smaller_lists.scss]
      dark: [darkly, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    code-fold: false
    code-summary: "Show the code"
