{
  "hash": "b3dd03c1d87656459c858b9a9b7dec56",
  "result": {
    "engine": "knitr",
    "markdown": "# Multiple Linear Regression\n\n\n\n> \"Life is really simple, but we insist on making it complicated.\"\n>\n> --- **Confucius**\n\nAfter reading this chapter you will be able to:\n\n- Construct and interpret linear regression models with more than one predictor.\n- Understand how regression models are derived using matrices.\n- Create interval estimates and perform hypothesis tests for multiple regression parameters.\n- Formulate and interpret interval estimates for the mean response under various conditions.\n- Compare nested models using an ANOVA F-Test.\n\nThe last two chapters we saw how to fit a model that assumed a linear relationship between a response variable and a single predictor variable. Specifically, we defined the simple linear regression model,\n\n$$\nY_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2)$.\n\nHowever, it is rarely the case that a dataset will have a single predictor variable. It is also rarely the case that a response variable will only depend on a single variable. So in this chapter, we will extend our current linear model to allow a response to depend on *multiple* predictors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# read the data from the web\nautompg <- read.table(\n  \"http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data\",\n  quote = \"\\\"\",\n  comment.char = \"\",\n  stringsAsFactors = FALSE)\n# give the dataframe headers\ncolnames(autompg) = c(\"mpg\", \"cyl\", \"disp\", \"hp\", \"wt\", \"acc\", \"year\", \"origin\", \"name\")\n# remove missing data, which is stored as \"?\"\nautompg <- subset(autompg, autompg$hp != \"?\")\n# remove the plymouth reliant, as it causes some issues\nautompg <- subset(autompg, autompg$name != \"plymouth reliant\")\n# give the dataset row names, based on the engine, year and name\nrownames(autompg) = paste(autompg$cyl, \"cylinder\", autompg$year, autompg$name)\n# remove the variable for name, as well as origin\nautompg <- subset(autompg, select = c(\"mpg\", \"cyl\", \"disp\", \"hp\", \"wt\", \"acc\", \"year\"))\n# change horsepower from character to numeric\nautompg$hp = as.numeric(autompg$hp)\n# check final structure of data\nstr(autompg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t390 obs. of  7 variables:\n $ mpg : num  18 15 18 16 17 15 14 14 14 15 ...\n $ cyl : int  8 8 8 8 8 8 8 8 8 8 ...\n $ disp: num  307 350 318 304 302 429 454 440 455 390 ...\n $ hp  : num  130 165 150 150 140 198 220 215 225 190 ...\n $ wt  : num  3504 3693 3436 3433 3449 ...\n $ acc : num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...\n $ year: int  70 70 70 70 70 70 70 70 70 70 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nWe will once again discuss a dataset with information about cars. [This dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data){target=\"_blank\"}, which can be found at the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG){target=\"_blank\"} contains a response variable `mpg` which stores the city fuel efficiency of cars, as well as several predictor variables for the attributes of the vehicles. We load the data, and perform some basic tidying before moving on to analysis.\n\nFor now we will focus on using two variables, `wt` and `year`, as predictor variables. That is, we would like to model the fuel efficiency (`mpg`) of a car as a function of its weight (`wt`) and model year (`year`). To do so, we will define the following linear model,\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\epsilon_i, \\qquad i = 1, 2, \\ldots, n\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2)$. In this notation we will define:\n\n- $x_{i1}$ as the weight (`wt`) of the $i$th car.\n- $x_{i2}$ as the model year (`year`) of the $i$th car.\n\nThe picture below will visualize what we would like to accomplish. The data points $(x_{i1}, x_{i2}, y_i)$ now exist in 3-dimensional space, so instead of fitting a line to the data, we will fit a plane. (We'll soon move to higher dimensions, so this will be the last example that is easy to visualize and think about this way.)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08_mlr_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=576}\n:::\n:::\n\n\nHow do we find such a plane? Well, we would like a plane that is as close as possible to the data points. That is, we would like it to minimize the errors it is making. How will we define these errors? Squared distance of course! So, we would like to minimize\n\n$$\nf(\\beta_0, \\beta_1, \\beta_2) = \\sum_{i = 1}^{n}(y_i - (\\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2}))^2\n$$\n\nwith respect to $\\beta_0$, $\\beta_1$, and $\\beta_2$. How do we do so? It is another straightforward multivariate calculus problem. All we have done is add an extra variable since we did this last time. So again, we take a derivative with respect to each of $\\beta_0$, $\\beta_1$, and $\\beta_2$ and set them equal to zero, then solve the resulting system of equations. That is,\n\n$$\n\\begin{aligned}\n\\frac{\\partial f}{\\partial \\beta_0} &= 0 \\\\\n\\frac{\\partial f}{\\partial \\beta_1} &= 0 \\\\\n\\frac{\\partial f}{\\partial \\beta_2} &= 0\n\\end{aligned}\n$$\n\nAfter doing so, we will once again obtain the **normal equations.**\n\n$$\n\\begin{aligned}\nn \\beta_0 + \\beta_1 \\sum_{i = 1}^{n} x_{i1} + \\beta_2 \\sum_{i = 1}^{n} x_{i2} &= \\sum_{i = 1}^{n} y_i  \\\\\n\\beta_0 \\sum_{i = 1}^{n} x_{i1} + \\beta_1 \\sum_{i = 1}^{n} x_{i1}^2 + \\beta_2 \\sum_{i = 1}^{n} x_{i1}x_{i2} &= \\sum_{i = 1}^{n} x_{i1}y_i \\\\\n\\beta_0 \\sum_{i = 1}^{n} x_{i2} + \\beta_1 \\sum_{i = 1}^{n} x_{i1}x_{i2} + \\beta_2 \\sum_{i = 1}^{n} x_{i2}^2 &= \\sum_{i = 1}^{n} x_{i2}y_i\n\\end{aligned}\n$$\n\nWe now have three equations and three variables, which we could solve, or we could simply let `R` solve for us.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmpg_model <- lm(mpg ~ wt + year, data = autompg)\ncoef(mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)            wt          year \n-14.637641945  -0.006634876   0.761401955 \n```\n\n\n:::\n:::\n\n\n$$\n\\hat{y} = -14.6376419 + -0.0066349 x_1 + 0.761402 x_2\n$$\n\nHere we have once again fit our model using `lm()`, however we have introduced a new syntactical element. The formula `mpg ~ wt + year` now reads: \"model the response variable `mpg` as a linear function of `wt` and `year`.\" That is, it will estimate an intercept, as well as slope coefficients for `wt` and `year`. We then extract these as we have done before using `coef()`.\n\nIn the multiple linear regression setting, some of the interpretations of the coefficients change slightly.\n\nHere, $\\hat{\\beta}_0 = -14.6376419$ is our estimate for $\\beta_0$, the mean miles per gallon for a car that weighs 0 pounds and was built in 1900. We see our estimate here is negative, which is a physical impossibility. However, this isn't unexpected, as we shouldn't expect our model to be accurate for cars from 1900 which weigh 0 pounds. (Because they never existed!) This isn't much of a change from SLR. That is, $\\beta_0$ is still simply the mean when all of the predictors are 0.\n\nThe interpretation of the coefficients in front of our predictors is slightly different than before. For example $\\hat{\\beta}_1 = -0.0066349$ is our estimate for $\\beta_1$, the average change in miles per gallon for an increase in weight ($x_{1}$) of one-pound **for a car of a certain model year**, that is, for a fixed value of $x_{2}$. Note that this coefficient is actually the same for any given value of $x_{2}$. Later, we will look at models that allow for a different change in mean response for different values of $x_{2}$. Also note that this estimate is negative, which we would expect since, in general, fuel efficiency decreases for larger vehicles. Recall that in the multiple linear regression setting, this interpretation is dependent on a fixed value for $x_{2}$, that is, \"for a car of a certain model year.\" It is possible that the indirect relationship between fuel efficiency and weight does not hold when an additional factor, say year, is included, and thus we could have the sign of our coefficient flipped.\n\nLastly, $\\hat{\\beta}_2 = 0.761402$ is our estimate for $\\beta_2$, the average change in miles per gallon for a one-year increase in model year ($x_{2}$) for a car of a certain weight, that is, for a fixed value of $x_{1}$. It is not surprising that the estimate is positive. We expect that as time passes and the years march on, technology would improve so that a car of a specific weight would get better mileage now as compared to their predecessors. And yet, the coefficient could have been negative because we are also including weight as variable, and not strictly as a fixed value. \n\n## Matrix Approach to Regression\n\nIn our above example we used two predictor variables, but it will only take a little more work to allow for an arbitrary number of predictor variables and derive their coefficient estimates. We can consider the model,\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_{p-1} x_{i(p-1)} + \\epsilon_i, \\qquad i = 1, 2, \\ldots, n\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2)$. In this model, there are $p - 1$ predictor variables, $x_1, x_2, \\cdots, x_{p-1}$. There are a total of $p$ $\\beta$-parameters and a single parameter $\\sigma^2$ for the variance of the errors. (It should be noted that almost as often, authors will use $p$ as the number of predictors, making the total number of $\\beta$ parameters $p+1$. This is always something you should be aware of when reading about multiple regression. There is not a standard that is used most often.)\n\nIf we were to stack together the $n$ linear equations that represent each $Y_i$ into a column vector, we get the following.\n\n$$\n\\begin{bmatrix}\nY_1   \\\\\nY_2   \\\\\n\\vdots\\\\\nY_n   \\\\\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n1      & x_{11}    & x_{12}    & \\cdots & x_{1(p-1)} \\\\\n1      & x_{21}    & x_{22}    & \\cdots & x_{2(p-1)} \\\\\n\\vdots & \\vdots    & \\vdots    &  & \\vdots \\\\\n1      & x_{n1}    & x_{n2}    & \\cdots & x_{n(p-1)} \\\\\n\\end{bmatrix}\n\\begin{bmatrix}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\beta_2 \\\\\n\\vdots \\\\\n\\beta_{p-1} \\\\\n\\end{bmatrix}\n+\n\\begin{bmatrix}\n\\epsilon_1   \\\\\n\\epsilon_2   \\\\\n\\vdots\\\\\n\\epsilon_n   \\\\\n\\end{bmatrix}\n$$\n\n$$\nY = X \\beta + \\epsilon\n$$\n\n$$\nY <- \\begin{bmatrix} Y_1 \\\\ Y_2 \\\\ \\vdots\\\\ Y_n \\end{bmatrix}, \\quad\nX <- \\begin{bmatrix}\n1      & x_{11}    & x_{12}    & \\cdots & x_{1(p-1)} \\\\\n1      & x_{21}    & x_{22}    & \\cdots & x_{2(p-1)} \\\\\n\\vdots & \\vdots    & \\vdots    &  & \\vdots \\\\\n1      & x_{n1}    & x_{n2}    & \\cdots & x_{n(p-1)} \\\\\n\\end{bmatrix}, \\quad\n\\beta = \\begin{bmatrix}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\beta_2 \\\\\n\\vdots \\\\\n\\beta_{p-1} \\\\\n\\end{bmatrix}, \\quad\n\\epsilon = \\begin{bmatrix} \\epsilon_1 \\\\ \\epsilon_2 \\\\ \\vdots\\\\ \\epsilon_n \\end{bmatrix}\n$$\n\nSo now with data,\n\n$$\ny = \\begin{bmatrix} y_1 \\\\ y_2 \\\\ \\vdots\\\\ y_n \\end{bmatrix}\n$$\n\nJust as before, we can estimate $\\beta$ by minimizing,\n\n$$\nf(\\beta_0, \\beta_1, \\beta_2, \\cdots, \\beta_{p-1}) = \\sum_{i = 1}^{n}(y_i - (\\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_{p-1} x_{i(p-1)}))^2,\n$$\n\nwhich would require taking $p$ derivatives, which result in the following **normal equations**.\n\n$$\n\\begin{bmatrix}\nn                           & \\sum_{i = 1}^{n} x_{i1}           & \\sum_{i = 1}^{n} x_{i2}           & \\cdots & \\sum_{i = 1}^{n} x_{i(p-1)}       \\\\\n\\sum_{i = 1}^{n} x_{i1}     & \\sum_{i = 1}^{n} x_{i1}^2         & \\sum_{i = 1}^{n} x_{i1}x_{i2}     & \\cdots & \\sum_{i = 1}^{n} x_{i1}x_{i(p-1)} \\\\\n\\vdots                      & \\vdots                            & \\vdots                            &        & \\vdots                            \\\\\n\\sum_{i = 1}^{n} x_{i(p-1)} & \\sum_{i = 1}^{n} x_{i(p-1)}x_{i1} & \\sum_{i = 1}^{n} x_{i(p-1)}x_{i2} & \\cdots & \\sum_{i = 1}^{n} x_{i(p-1)}^2     \\\\\n\\end{bmatrix}\n\\begin{bmatrix}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\vdots \\\\\n\\beta_{p-1} \\\\\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n\\sum_{i = 1}^{n} y_i \\\\\n\\sum_{i = 1}^{n} x_{i1}y_i \\\\\n\\vdots \\\\\n\\sum_{i = 1}^{n} x_{i(p-1)}y_i \\\\\n\\end{bmatrix}\n$$\n\nThe normal equations can be written much more succinctly in matrix notation,\n\n$$\nX^\\top X \\beta = X^\\top y.\n$$\n\nWe can then solve this expression by multiplying both sides by the inverse of $X^\\top X$, which exists, provided the columns of $X$ are linearly independent. Then as always, we denote our solution with a hat.\n\n$$\n\\hat{\\beta} = \\left(  X^\\top X  \\right)^{-1}X^\\top y\n$$\n\nTo verify that this is what `R` has done for us in the case of two predictors, we create an $X$ matrix. Note that the first column is all 1s, and the remaining columns contain the data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- nrow(autompg)\np <- length(coef(mpg_model))\nX <- cbind(rep(1, n), autompg$wt, autompg$year)\ny <- autompg$mpg\n\n(beta_hat = solve(t(X) %*% X) %*% t(X) %*% y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1]\n[1,] -14.637641945\n[2,]  -0.006634876\n[3,]   0.761401955\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)            wt          year \n-14.637641945  -0.006634876   0.761401955 \n```\n\n\n:::\n:::\n\n\n$$\n\\hat{\\beta} = \\begin{bmatrix}\n-14.6376419    \\\\\n-0.0066349    \\\\\n0.761402    \\\\\n\\end{bmatrix}\n$$\n\nIn our new notation, the fitted values can be written\n\n$$\n\\hat{y} = X \\hat{\\beta}.\n$$\n\n$$\n\\hat{y} = \\begin{bmatrix} \\hat{y}_1 \\\\ \\hat{y}_2 \\\\ \\vdots\\\\ \\hat{y}_n \\end{bmatrix}\n$$\n\nThen, we can create a vector for the residual values,\n\n$$\ne \n= \\begin{bmatrix} e_1 \\\\ e_2 \\\\ \\vdots\\\\ e_n \\end{bmatrix} \n= \\begin{bmatrix} y_1 \\\\ y_2 \\\\ \\vdots\\\\ y_n \\end{bmatrix} - \\begin{bmatrix} \\hat{y}_1 \\\\ \\hat{y}_2 \\\\ \\vdots\\\\ \\hat{y}_n \\end{bmatrix}.\n$$\n\nAnd lastly, we can update our estimate for $\\sigma^2$.\n\n$$\ns_e^2 = \\frac{\\sum_{i=1}^n (y_i - \\hat{y}_i)^2}{n - p} = \\frac{e^\\top e}{n-p}\n$$\n\nRecall, we like this estimate because it is unbiased, that is,\n\n$$\n\\text{E}[s_e^2] = \\sigma^2\n$$\n\nNote that the change from the SLR estimate to now is in the denominator. Specifically we now divide by $n - p$ instead of $n - 2$. Or actually, we should note that in the case of SLR, there are two $\\beta$ parameters and thus $p = 2$. \n\nAlso note that if we fit the model $Y_i = \\beta + \\epsilon_i$ that $\\hat{y} = \\bar{y}$ and $p = 1$ and $s_e^2$ would become\n\n$$\ns_e^2 = \\frac{\\sum_{i=1}^n (y_i - \\bar{y})^2}{n - 1}\n$$\n\nwhich is likely the very first sample variance you saw in a mathematical statistics class. The same reason for $n - 1$ in this case, that we estimated one parameter, so we lose one degree of freedom. Now, in general, we are estimating $p$ parameters, the $\\beta$ parameters, so we lose $p$ degrees of freedom.\n\nAlso, recall that most often we will be interested in $s_e$, the residual standard error as `R` calls it,\n\n$$\ns_e = \\sqrt{\\frac{\\sum_{i=1}^n (y_i - \\hat{y}_i)^2}{n - p}}.\n$$\n\nIn `R`, we could directly access $s_e$ for a fitted model, as we have seen before.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mpg_model)$sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.431367\n```\n\n\n:::\n:::\n\n\nAnd we can now verify that our math above is indeed calculating the same quantities.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny_hat <- X %*% solve(t(X) %*% X) %*% t(X) %*% y\ne <- y - y_hat\nsqrt(t(e) %*% e / (n - p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 3.431367\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(sum((y - y_hat) ^ 2) / (n - p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.431367\n```\n\n\n:::\n:::\n\n\n## Sampling Distribution\n\nAs we can see in the output below, the results of calling `summary()` are similar to SLR, but there are some differences, most obviously a new row for the added predictor variable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ wt + year, data = autompg)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.852 -2.292 -0.100  2.039 14.325 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.464e+01  4.023e+00  -3.638 0.000312 ***\nwt          -6.635e-03  2.149e-04 -30.881  < 2e-16 ***\nyear         7.614e-01  4.973e-02  15.312  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.431 on 387 degrees of freedom\nMultiple R-squared:  0.8082,\tAdjusted R-squared:  0.8072 \nF-statistic: 815.6 on 2 and 387 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nTo understand these differences in detail, we will need to first obtain the sampling distribution of $\\hat{\\beta}$.\n\nThe derivation of the sampling distribution of $\\hat{\\beta}$ involves the [multivariate normal distribution. These brief notes from semesters past](notes/mvn.pdf) give a basic overview. These are simply for your information, as we will not present the derivation in full here.\n\nOur goal now is to obtain the distribution of the $\\hat{\\beta}$ vector,\n\n$$\n\\hat{\\beta} = \\begin{bmatrix}\n\\hat{\\beta}_0 \\\\\n\\hat{\\beta}_1 \\\\\n\\hat{\\beta}_2 \\\\\n\\vdots \\\\\n\\hat{\\beta}_{p-1} \\end{bmatrix}\n$$\n\nRecall from last time that when discussing sampling distributions, we now consider $\\hat{\\beta}$ to be a random vector, thus we use $Y$ instead of the data vector $y$.\n\n$$\n\\hat{\\beta} = \\left(  X^\\top X  \\right)^{-1}X^\\top Y\n$$\n\nThen it is a consequence of the multivariate normal distribution that,\n\n$$\n\\hat{\\beta} \\sim N\\left(\\beta, \\sigma^2 \\left(X^\\top X\\right)^{-1}  \\right).\n$$\n\nWe then have\n\n$$\n\\text{E}[\\hat{\\beta}] = \\beta\n$$\n\nand for any $\\hat{\\beta}_j$ we have\n\n$$\n\\text{E}[\\hat{\\beta}_j] = \\beta_j.\n$$\n\nWe also have\n\n$$\n\\text{Var}[\\hat{\\beta}] = \\sigma^2 \\left(  X^\\top X  \\right)^{-1}\n$$\n\nand for any $\\hat{\\beta}_j$ we have\n\n$$\n\\text{Var}[\\hat{\\beta}_j] = \\sigma^2 C_{jj}\n$$\n\nwhere \n\n$$\nC = \\left(X^\\top X\\right)^{-1}\n$$\n\nand the elements of $C$ are denoted\n\n$$\nC <- \\begin{bmatrix}\nC_{00}     & C_{01}     & C_{02}     & \\cdots & C_{0(p-1)}     \\\\\nC_{10}     & C_{11}     & C_{12}     & \\cdots & C_{1(p-1)}     \\\\\nC_{20}     & C_{21}     & C_{22}     & \\cdots & C_{2(p-1)}     \\\\\n\\vdots     & \\vdots     & \\vdots     &        & \\vdots         \\\\\nC_{(p-1)0} & C_{(p-1)1} & C_{(p-1)2} & \\cdots & C_{(p-1)(p-1)} \\\\\n\\end{bmatrix}.\n$$\n\nEssentially, the diagonal elements correspond to the $\\beta$ vector.\n\nThen the standard error for the $\\hat{\\beta}$ vector is given by\n\n$$\n\\text{SE}[\\hat{\\beta}] = s_e \\sqrt{\\left(  X^\\top X  \\right)^{-1}}\n$$\n\nand for a particular $\\hat{\\beta}_j$\n\n$$\n\\text{SE}[\\hat{\\beta}_j] = s_e \\sqrt{C_{jj}}.\n$$\n\nLastly, each of the $\\hat{\\beta}_j$ follows a normal distribution,\n\n$$\n\\hat{\\beta}_j \\sim N\\left(\\beta_j, \\sigma^2 C_{jj}  \\right).\n$$\n\nthus\n\n$$\n\\frac{\\hat{\\beta}_j - \\beta_j}{s_e \\sqrt{C_{jj}}} \\sim t_{n-p}.\n$$\n\nNow that we have the necessary distributional results, we can move on to perform tests and make interval estimates.\n\n### Single Parameter Tests\n\nThe first test we will see is a test for a single $\\beta_j$.\n\n$$\nH_0: \\beta_j = 0 \\quad \\text{vs} \\quad H_1: \\beta_j \\neq 0\n$$\n\nAgain, the test statistic takes the form\n\n$$\n\\text{TS} = \\frac{\\text{EST} - \\text{HYP}}{\\text{SE}}.\n$$\n\nIn particular,\n\n$$\nt = \\frac{\\hat{\\beta}_j - \\beta_j}{\\text{SE}[\\hat{\\beta}_j]} = \\frac{\\hat{\\beta}_j-0}{s_e\\sqrt{C_{jj}}},\n$$\n\nwhich, under the null hypothesis, follows a $t$ distribution with $n - p$ degrees of freedom.\n\nRecall our model for `mpg`, \n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\epsilon_i, \\qquad i = 1, 2, \\ldots, n\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2)$. \n\n- $x_{i1}$ as the weight (`wt`) of the $i$th car.\n- $x_{i2}$ as the model year (`year`) of the $i$th car.\n\nThen the test\n\n$$\nH_0: \\beta_1 = 0 \\quad \\text{vs} \\quad H_1: \\beta_1 \\neq 0\n$$\n\ncan be found in the `summary()` output, in particular:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mpg_model)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error    t value      Pr(>|t|)\n(Intercept) -14.637641945 4.0233913563  -3.638135  3.118311e-04\nwt           -0.006634876 0.0002148504 -30.881372 1.850466e-106\nyear          0.761401955 0.0497265950  15.311765  1.036597e-41\n```\n\n\n:::\n:::\n\n\nThe estimate (`Estimate`), standard error (`Std. Error`), test statistic (`t value`), and p-value (`Pr(>|t|)`) for this test are displayed in the second row, labeled `wt`. Remember that the p-value given here is specifically for a two-sided test, where the hypothesized value is 0.\n\nAlso note in this case, by hypothesizing that $\\beta_1 = 0$ the null and alternative essentially specify two different models:\n\n- $H_0$: $Y = \\beta_0 + \\beta_2 x_{2} + \\epsilon$\n- $H_1$: $Y = \\beta_0 + \\beta_1 x_{1} + \\beta_2 x_{2} + \\epsilon$\n\nThis is important. We are not simply testing whether or not there is a relationship between weight and fuel efficiency. We are testing if there is a relationship between weight and fuel efficiency, given that a term for year is in the model. (Note, we dropped some indexing here, for readability.)\n\n### Confidence Intervals\n\nSince $\\hat{\\beta}_j$ is our estimate for $\\beta_j$ and we have\n\n$$\n\\text{E}[\\hat{\\beta}_j] = \\beta_j\n$$\n\nas well as the standard error,\n\n$$\n\\text{SE}[\\hat{\\beta}_j] = s_e\\sqrt{C_{jj}}\n$$\n\nand the sampling distribution of $\\hat{\\beta}_j$ is Normal, then we can easily construct confidence intervals for each of the $\\hat{\\beta}_j$.\n\n$$\n\\hat{\\beta}_j \\pm t_{\\alpha/2, n - p} \\cdot s_e\\sqrt{C_{jj}}\n$$\n\nWe can find these in `R` using the same method as before. Now there will simply be additional rows for the additional $\\beta$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(mpg_model, level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    0.5 %       99.5 %\n(Intercept) -25.052563681 -4.222720208\nwt           -0.007191036 -0.006078716\nyear          0.632680051  0.890123859\n```\n\n\n:::\n:::\n\n\n### Confidence Intervals for Mean Response\n\nAs we saw in SLR, we can create confidence intervals for the mean response, that is, an interval estimate for $\\text{E}[Y \\mid X = x]$. In SLR, the mean of $Y$ was only dependent on a single value $x$. Now, in multiple regression, $\\text{E}[Y \\mid X = x]$ is dependent on the value of each of the predictors, so we define the vector $x_0$ to be, \n\n$$\nx_{0} = \\begin{bmatrix}\n1 \\\\\nx_{01} \\\\\nx_{02} \\\\\n\\vdots \\\\\nx_{0(p-1)} \\\\\n\\end{bmatrix}.\n$$\n\nThen our estimate of $\\text{E}[Y \\mid X = x_0]$ for a set of values $x_0$ is given by\n\n$$\n\\begin{aligned}\n\\hat{y}(x_0) &= x_{0}^\\top\\hat{\\beta} \\\\\n&= \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{01} + \\hat{\\beta}_2 x_{02} + \\cdots + \\hat{\\beta}_{p-1} x_{0(p-1)}.\n\\end{aligned}\n$$\n\nAs with SLR, this is an unbiased estimate.\n\n$$\n\\begin{aligned}\n\\text{E}[\\hat{y}(x_0)] &= x_{0}^\\top\\beta \\\\\n&= \\beta_0 + \\beta_1 x_{01} + \\beta_2 x_{02} + \\cdots + \\beta_{p-1} x_{0(p-1)}\n\\end{aligned}\n$$\n\nTo make an interval estimate, we will also need its standard error.\n\n$$\n\\text{SE}[\\hat{y}(x_0)] = s_e \\sqrt{x_{0}^\\top\\left(X^\\top X\\right)^{-1}x_{0}}\n$$\n\nPutting it all together, we obtain a confidence interval for the mean response.\n\n$$\n\\hat{y}(x_0) \\pm t_{\\alpha/2, n - p} \\cdot s_e \\sqrt{x_{0}^\\top\\left(X^\\top X\\right)^{-1}x_{0}}\n$$\n\nThe math has changed a bit, but the process in `R` remains almost identical. Here, we create a data frame for two additional cars. One car that weighs 3500 pounds produced in 1976, as well as a second car that weighs 5000 pounds which was produced in 1981.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_cars <- data.frame(wt = c(3500, 5000), year = c(76, 81))\nnew_cars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    wt year\n1 3500   76\n2 5000   81\n```\n\n\n:::\n:::\n\n\nWe can then use the `predict()` function with `interval = \"confidence\"` to obtain intervals for the mean fuel efficiency for both new cars. Again, it is important to make the data passed to `newdata` a data frame, so that `R` knows which values are for which variables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(mpg_model, newdata = new_cars, interval = \"confidence\", level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit     lwr      upr\n1 20.00684 19.4712 20.54248\n2 13.86154 12.3341 15.38898\n```\n\n\n:::\n:::\n\n\n`R` then reports the estimate $\\hat{y}(x_0)$ (`fit`) for each, as well as the lower (`lwr`) and upper (`upr`) bounds for the interval at a desired level (99%).\n\nA word of caution here: one of these estimates is good while one is suspect.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_cars$wt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3500 5000\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(autompg$wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1613 5140\n```\n\n\n:::\n:::\n\n\nNote that both of the weights of the new cars are within the range of observed values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_cars$year\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 76 81\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(autompg$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70 82\n```\n\n\n:::\n:::\n\n\nAs are the years of each of the new cars.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(year ~ wt, data = autompg, pch = 20, col = \"dodgerblue\", cex = 1.5)\npoints(new_cars, col = \"darkorange\", cex = 3, pch = \"X\")\n```\n\n::: {.cell-output-display}\n![](08_mlr_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nHowever, we have to consider weight and year together now. And based on the above plot, one of the new cars is within the \"blob\" of observed values, while the other, the car from 1981 weighing 5000 pounds, is noticeably outside of the observed values. This is a hidden extrapolation which you should be aware of when using multiple regression.\n\nShifting gears back to the new data pair that can be reasonably estimated, we do a quick verification of some of the mathematics in `R`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx0 <- c(1, 3500, 76)\nx0 %*% beta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 20.00684\n```\n\n\n:::\n:::\n\n\n$$\nx_{0} = \\begin{bmatrix}\n1    \\\\\n3500 \\\\\n76   \\\\\n\\end{bmatrix}\n$$\n\n$$\n\\hat{\\beta} = \\begin{bmatrix}\n-14.6376419    \\\\\n-0.0066349    \\\\\n0.761402    \\\\\n\\end{bmatrix}\n$$\n\n$$\n\\hat{y}(x_0)  = x_{0}^\\top\\hat{\\beta} = \n\\begin{bmatrix}\n1    &\n3500 &\n76   \\\\\n\\end{bmatrix}\n\\begin{bmatrix}\n-14.6376419    \\\\\n-0.0066349    \\\\\n0.761402    \\\\\n\\end{bmatrix}= 20.0068411\n$$\n\nAlso note that, using a particular value for $x_0$, we can essentially extract certain $\\hat{\\beta}_j$ values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbeta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1]\n[1,] -14.637641945\n[2,]  -0.006634876\n[3,]   0.761401955\n```\n\n\n:::\n\n```{.r .cell-code}\nx0 <- c(0, 0, 1)\nx0 %*% beta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 0.761402\n```\n\n\n:::\n:::\n\n\nWith this in mind, confidence intervals for the individual $\\hat{\\beta}_j$ are actually a special case of a confidence interval for mean response. \n\n### Prediction Intervals\n\nAs with SLR, creating prediction intervals involves one slight change to the standard error to account for the fact that we are now considering an observation, instead of a mean.\n\nHere we use $\\hat{y}(x_0)$ to estimate $Y_0$, a new observation of $Y$ at the predictor vector $x_0$.\n\n$$\n\\begin{aligned}\n\\hat{y}(x_0) &= x_{0}^\\top\\hat{\\beta} \\\\\n&= \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{01} + \\hat{\\beta}_2 x_{02} + \\cdots + \\hat{\\beta}_{p-1} x_{0(p-1)}\n\\end{aligned}\n$$\n\n$$\n\\begin{aligned}\n\\text{E}[\\hat{y}(x_0)] &= x_{0}^\\top\\beta \\\\\n&= \\beta_0 + \\beta_1 x_{01} + \\beta_2 x_{02} + \\cdots + \\beta_{p-1} x_{0(p-1)}\n\\end{aligned}\n$$\n\nAs we did with SLR, we need to account for the additional variability of an observation about its mean.\n\n$$\n\\text{SE}[\\hat{y}(x_0) + \\epsilon] = s_e \\sqrt{1 + x_{0}^\\top\\left(X^\\top X\\right)^{-1}x_{0}}\n$$\n\nThen we arrive at our updated prediction interval for MLR.\n\n$$\n\\hat{y}(x_0) \\pm t_{\\alpha/2, n - p} \\cdot s_e \\sqrt{1 + x_{0}^\\top\\left(X^\\top X\\right)^{-1}x_{0}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_cars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    wt year\n1 3500   76\n2 5000   81\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(mpg_model, newdata = new_cars, interval = \"prediction\", level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit       lwr      upr\n1 20.00684 11.108294 28.90539\n2 13.86154  4.848751 22.87432\n```\n\n\n:::\n:::\n\n\n## Significance of Regression\n\nThe decomposition of variation that we had seen in SLR still holds for MLR.\n\n$$\n\\sum_{i=1}^{n}(y_i - \\bar{y})^2 = \\sum_{i=1}^{n}(y_i - \\hat{y}_i)^2 + \\sum_{i=1}^{n}(\\hat{y}_i - \\bar{y})^2\n$$\n\nThat is,\n\n$$\n\\text{SST} = \\text{SSE} + \\text{SSReg}.\n$$\n\nThis means that we can still calculate $R^2$ in the same manner as before, which `R` continues to do automatically.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mpg_model)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8082355\n```\n\n\n:::\n:::\n\n\nThe interpretation changes slightly as compared to SLR. In this MLR case, we say that $80.82\\%$ of the observed variation in miles per gallon is explained by the linear relationship with the two predictor variables, weight and year.\n\nIn multiple regression, the significance of regression test is\n\n$$\nH_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_{p - 1} = 0.\n$$\n\nHere, we see that the null hypothesis sets all of the $\\beta_j$ equal to 0, *except* the intercept, $\\beta_0$. We could then say that the null model, or \"model under the null hypothesis\" is\n\n$$\nY_i = \\beta_0 + \\epsilon_i.\n$$\n\nThis is a model where the *regression* is insignificant. **None** of the predictors have a significant linear relationship with the response. Notationally, we will denote the fitted values of this model as $\\hat{y}_{0i}$, which in this case happens to be:\n\n$$\n\\hat{y}_{0i} = \\bar{y}.\n$$\n\nThe alternative hypothesis here is that at least one of the $\\beta_j$ from the null hypothesis is not 0.\n\n$$\nH_1: \\text{At least one of } \\beta_j \\neq 0, j = 1, 2, \\cdots, (p-1)\n$$\n\nWe could then say that the full model, or \"model under the alternative hypothesis\" is\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_{(p-1)} x_{i(p-1)} + \\epsilon_i\n$$\n\nThis is a model where the regression is significant. **At least one** of the predictors has a significant linear relationship with the response. There is some linear relationship between $y$ and the predictors, $x_1, x_2, \\ldots, x_{p - 1}$.\n\nWe will denote the fitted values of this model as $\\hat{y}_{1i}$.\n\nTo develop the $F$ test for the significance of the regression, we will arrange the variance decomposition into an ANOVA table.\n\n| Source     | Sum of Squares  | Degrees of Freedom | Mean Square | $F$ |\n|------------|-----------------|------------|-----------|-----------|\n| Regression | $\\sum_{i=1}^{n}(\\hat{y}_{1i} - \\bar{y})^2$ | $p - 1$ | $\\text{SSReg} / (p - 1)$ | $\\text{MSReg} / \\text{MSE}$ |\n| Error      | $\\sum_{i=1}^{n}(y_i - \\hat{y}_{1i})^2$     | $n - p$ | $\\text{SSE} / (n - p)$ |             |\n| Total      | $\\sum_{i=1}^{n}(y_i - \\bar{y})^2$       | $n - 1$ |                 |             |\n\nIn summary, the $F$ statistic is\n\n$$\nF = \\frac{\\sum_{i=1}^{n}(\\hat{y}_{1i} - \\bar{y})^2 / (p - 1)}{\\sum_{i=1}^{n}(y_i - \\hat{y}_{1i})^2 / (n - p)},\n$$\n\nand the p-value is calculated as\n\n$$\nP(F_{p-1, n-p} > F)\n$$\n\nsince we reject for large values of $F$. A large value of the statistic corresponds to a large portion of the variance being explained by the regression. Here $F_{p-1, n-p}$ represents a random variable which follows an $F$ distribution with $p - 1$ and $n - p$ degrees of freedom.\n\nTo perform this test in `R`, we first explicitly specify the two models in `R` and save the results in different variables. We then use `anova()` to compare the two models, giving `anova()` the null model first and the alternative (full) model second. (Specifying the full model first will result in the same p-value, but some nonsensical intermediate values.)\n\nIn this case,\n\n- $H_0$: $Y_i = \\beta_0 + \\epsilon_i$\n- $H_1$: $Y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\epsilon_i$\n\nThat is, in the null model, we use neither of the predictors, whereas in the full (alternative) model, at least one of the predictors is useful.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_mpg_model <- lm(mpg ~ 1, data = autompg)\nfull_mpg_model <- lm(mpg ~ wt + year, data = autompg)\nanova(null_mpg_model, full_mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: mpg ~ 1\nModel 2: mpg ~ wt + year\n  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    \n1    389 23761.7                                  \n2    387  4556.6  2     19205 815.55 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nFirst, notice that `R` does not display the results in the same manner as the table above. More important than the layout of the table are its contents. We see that the value of the $F$ statistic is 815.55, and the p-value is extremely low, so we reject the null hypothesis at any reasonable $\\alpha$ and say that the regression is significant. At least one of `wt` or `year` has a useful linear relationship with `mpg`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ wt + year, data = autompg)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.852 -2.292 -0.100  2.039 14.325 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.464e+01  4.023e+00  -3.638 0.000312 ***\nwt          -6.635e-03  2.149e-04 -30.881  < 2e-16 ***\nyear         7.614e-01  4.973e-02  15.312  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.431 on 387 degrees of freedom\nMultiple R-squared:  0.8082,\tAdjusted R-squared:  0.8072 \nF-statistic: 815.6 on 2 and 387 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nNotice that the value reported in the row for `F-statistic` is indeed the $F$ test statistic for the significance of regression test, and additionally it reports the two relevant degrees of freedom.\n\nAlso, note that none of the individual $t$-tests are equivalent to the $F$-test as they were in SLR. This equivalence only holds for SLR because the individual test for $\\beta_1$ is the same as testing for all non-intercept parameters, since there is only one.\n\nWe can also verify the sums of squares and degrees of freedom directly in `R`. You should match these to the table from `R` and use this to match `R`'s output to the written table above. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# SSReg\nsum((fitted(full_mpg_model) - fitted(null_mpg_model)) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19205.03\n```\n\n\n:::\n\n```{.r .cell-code}\n# SSE\nsum(resid(full_mpg_model) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4556.646\n```\n\n\n:::\n\n```{.r .cell-code}\n# SST\nsum(resid(null_mpg_model) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23761.67\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Regression\nlength(coef(full_mpg_model)) - length(coef(null_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Error\nlength(resid(full_mpg_model)) - length(coef(full_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 387\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Total\nlength(resid(null_mpg_model)) - length(coef(null_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 389\n```\n\n\n:::\n:::\n\n\n## Nested Models\n\nThe significance of regression test is actually a special case of testing what we will call **nested models**. More generally we can compare two models, where one model is \"nested\" inside the other, meaning one model contains a subset of the predictors from only the larger model.\n\nConsider the following full model,\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_{(p-1)} x_{i(p-1)} + \\epsilon_i\n$$\n\nThis model has $p - 1$ predictors, for a total of $p$ $\\beta$-parameters. We will denote the fitted values of this model as $\\hat{y}_{1i}$.\n\nLet the null model be\n\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_{(q-1)} x_{i(q-1)} + \\epsilon_i\n$$\n\nwhere $q < p$. This model has $q - 1$ predictors, for a total of $q$ $\\beta$-parameters. We will denote the fitted values of this model as $\\hat{y}_{0i}$.\n\nThe difference between these two models can be codified by the null hypothesis of a test.\n\n$$\nH_0: \\beta_q = \\beta_{q+1} = \\cdots = \\beta_{p - 1} = 0.\n$$\n\nSpecifically, the $\\beta$-parameters from the full model that are not in the null model are zero. The resulting model, which is nested, is the null model.\n\nWe can then perform this test using an $F$-test, which is the result of the following ANOVA table.\n\n| Source | Sum of Squares  | Degrees of Freedom | Mean Square | $F$ |\n|--------|-----------------|------------|-----------|-----------|\n| Diff   | $\\sum_{i=1}^{n}(\\hat{y}_{1i} - \\hat{y}_{0i})^2$ | $p - q$ | $\\text{SSD}   / (p - q)$ | $\\text{MSD} / \\text{MSE}$ |\n| Full   | $\\sum_{i=1}^{n}(y_i - \\hat{y}_{1i})^2$          | $n - p$ | $\\text{SSE}   / (n - p)$ |             |\n| Null   | $\\sum_{i=1}^{n}(y_i - \\hat{y}_{0i})^2$          | $n - q$ |                   |             |\n\n$$\nF = \\frac{\\sum_{i=1}^{n}(\\hat{y}_{1i} - \\hat{y}_{0i})^2 / (p - q)}{\\sum_{i=1}^{n}(y_i - \\hat{y}_{1i})^2 / (n - p)}.\n$$\n\nNotice that the row for \"Diff\" compares the sum of the squared differences of the fitted values. The degrees of freedom is then the difference of the number of $\\beta$-parameters estimated between the two models.\n\nFor example, the `autompg` dataset has a number of additional variables that we have yet to use.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnames(autompg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mpg\"  \"cyl\"  \"disp\" \"hp\"   \"wt\"   \"acc\"  \"year\"\n```\n\n\n:::\n:::\n\n\nWe'll continue to use `mpg` as the response, but now we will consider two different models.\n\n- Full: `mpg ~ wt + year + cyl + disp + hp + acc`\n- Null: `mpg ~ wt + year`\n\nNote that these are nested models, as the null model contains a subset of the predictors from the full model, and no additional predictors. Both models have an intercept $\\beta_0$ as well as a coefficient in front of each of the predictors. We could then write the null hypothesis for comparing these two models as,\n\n$$\nH_0: \\beta_{\\texttt{cyl}} = \\beta_{\\texttt{disp}} = \\beta_{\\texttt{hp}} = \\beta_{\\texttt{acc}} = 0\n$$\n\nThe alternative is simply that at least one of the $\\beta_{j}$ from the null is not 0.\n\nTo perform this test in `R` we first define both models, then give them to the `anova()` commands.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_mpg_model <- lm(mpg ~ wt + year, data = autompg)\n#full_mpg_model = lm(mpg ~ wt + year + cyl + disp + hp + acc, data = autompg)\nfull_mpg_model <- lm(mpg ~ ., data = autompg)\nanova(null_mpg_model, full_mpg_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: mpg ~ wt + year\nModel 2: mpg ~ cyl + disp + hp + wt + acc + year\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1    387 4556.6                           \n2    383 4530.5  4     26.18 0.5533 0.6967\n```\n\n\n:::\n:::\n\n\nHere we have used the formula `mpg ~ .` to define to full model. This is the same as the commented out line. Specifically, this is a common shortcut in `R` which reads, \"model `mpg` as the response with each of the remaining variables in the data frame as predictors.\"\n\nHere we see that the value of the $F$ statistic is 0.553, and the p-value is very large, so we fail to reject the null hypothesis at any reasonable $\\alpha$ and say that none of `cyl`, `disp`, `hp`, and `acc` are significant with `wt` and `year` already in the model.\n\nAgain, we verify the sums of squares and degrees of freedom directly in `R`. You should match these to the table from `R`, and use this to match `R`'s output to the written table above. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# SSDiff\nsum((fitted(full_mpg_model) - fitted(null_mpg_model)) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26.17981\n```\n\n\n:::\n\n```{.r .cell-code}\n# SSE (For Full)\nsum(resid(full_mpg_model) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4530.466\n```\n\n\n:::\n\n```{.r .cell-code}\n# SST (For Null)\nsum(resid(null_mpg_model) ^ 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4556.646\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Diff\nlength(coef(full_mpg_model)) - length(coef(null_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Full\nlength(resid(full_mpg_model)) - length(coef(full_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 383\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degrees of Freedom: Null\nlength(resid(null_mpg_model)) - length(coef(null_mpg_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 387\n```\n\n\n:::\n:::\n\n\n## Simulation\n\nSince we ignored the derivation of certain results, we will again use simulation to convince ourselves of some of the above results. In particular, we will simulate samples of size `n = 100` from the model\n\n$$\nY_i = 5 + -2 x_{i1} + 6 x_{i2} + \\epsilon_i, \\qquad i = 1, 2, \\ldots, n\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2 = 16)$. Here we have two predictors, so $p = 3$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1337)\nn <- 100 # sample size\np <- 3\n\nbeta_0 <- 5\nbeta_1 <- -2\nbeta_2 <- 6\nsigma <- 4\n```\n:::\n\n\nAs is the norm with regression, the $x$ values are considered fixed and known quantities, so we will simulate those first, and they remain the same for the rest of the simulation study. Also note we create an `x0` which is all `1`, which we need to create our `X` matrix. If you look at the matrix formulation of regression, this unit vector of all `1`s is a \"predictor\" that puts the intercept into the model. We also calculate the `C` matrix for later use.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx0 <- rep(1, n)\nx1 <- sample(seq(1, 10, length = n))\nx2 <- sample(seq(1, 10, length = n))\nX <- cbind(x0, x1, x2)\nC <- solve(t(X) %*% X)\n```\n:::\n\n\nWe then simulate the response according the model above. Lastly, we place the two predictors and response into a data frame. Note that we do **not** place `x0` in the data frame. This is a result of `R` adding an intercept by default.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neps <- rnorm(n, mean = 0, sd = sigma)\ny <- beta_0 + beta_1 * x1 + beta_2 * x2 + eps\nsim_data <- data.frame(x1, x2, y)\n```\n:::\n\n\nPlotting this data and fitting the regression produces the following plot.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08_mlr_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=576}\n:::\n:::\n\n\nWe then calculate\n\n$$\n\\hat{\\beta} = \\left(  X^\\top X  \\right)^{-1}X^\\top y.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(beta_hat = C %*% t(X) %*% y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        [,1]\nx0  7.290735\nx1 -2.282176\nx2  5.843424\n```\n\n\n:::\n:::\n\n\nNotice that these values are the same as the coefficients found using `lm()` in `R`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(lm(y ~ x1 + x2, data = sim_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)          x1          x2 \n   7.290735   -2.282176    5.843424 \n```\n\n\n:::\n:::\n\n\nAlso, these values are close to what we would expect.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(beta_0, beta_1, beta_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5 -2  6\n```\n\n\n:::\n:::\n\n\nWe then calculated the fitted values in order to calculate $s_e$, which we see is the same as the `sigma` which is returned by `summary()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny_hat <- X %*% beta_hat\n(s_e = sqrt(sum((y - y_hat) ^ 2) / (n - p)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.294307\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lm(y ~ x1 + x2, data = sim_data))$sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.294307\n```\n\n\n:::\n:::\n\n\nSo far so good. Everything checks out. Now we will finally simulate from this model repeatedly in order to obtain an empirical distribution of $\\hat{\\beta}_2$.\n\nWe expect $\\hat{\\beta}_2$ to follow a normal distribution,\n\n$$\n\\hat{\\beta}_2 \\sim N\\left(\\beta_2, \\sigma^2 C_{22}  \\right).\n$$\n\nIn this case,\n\n$$\n\\hat{\\beta}_2 \\sim N\\left(\\mu = 6, \\sigma^2 = 16 \\times 0.0014534 = 0.0232549  \\right).\n$$\n\n$$\n\\hat{\\beta}_2 \\sim N\\left(\\mu = 6, \\sigma^2 = 0.0232549  \\right).\n$$\n\nNote that $C_{22}$ corresponds to the element in the **third** row and **third** column since $\\beta_2$ is the **third** parameter in the model and because `R` is indexed starting at `1`. However, we index the $C$ matrix starting at `0` to match the diagonal elements to the corresponding $\\beta_j$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nC[3, 3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00145343\n```\n\n\n:::\n\n```{.r .cell-code}\nC[2 + 1, 2 + 1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00145343\n```\n\n\n:::\n\n```{.r .cell-code}\nsigma ^ 2 * C[2 + 1, 2 + 1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02325487\n```\n\n\n:::\n:::\n\n\nWe now perform the simulation a large number of times. Each time, we update the `y` variable in the data frame, leaving the `x` variables the same. We then fit a model, and store $\\hat{\\beta}_2$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnum_sims <- 10000\nbeta_hat_2 <- rep(0, num_sims)\nfor(i in 1:num_sims) {\n  eps           = rnorm(n, mean = 0 , sd = sigma)\n  sim_data$y    = beta_0 * x0 + beta_1 * x1 + beta_2 * x2 + eps\n  fit           = lm(y ~ x1 + x2, data = sim_data)\n  beta_hat_2[i] = coef(fit)[3]\n}\n```\n:::\n\n\nWe then see that the mean of the simulated values is close to the true value of $\\beta_2$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(beta_hat_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.999723\n```\n\n\n:::\n\n```{.r .cell-code}\nbeta_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\nWe also see that the variance of the simulated values is close to the true variance of $\\hat{\\beta}_2$.\n\n$$\n\\text{Var}[\\hat{\\beta}_2] = \\sigma^2 \\cdot C_{22} = 16 \\times 0.0014534 = 0.0232549\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(beta_hat_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02343408\n```\n\n\n:::\n\n```{.r .cell-code}\nsigma ^ 2 * C[2 + 1, 2 + 1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02325487\n```\n\n\n:::\n:::\n\n\nThe standard deviations found from the simulated data and the parent population are also very close.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsd(beta_hat_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1530819\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(sigma ^ 2 * C[2 + 1, 2 + 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1524955\n```\n\n\n:::\n:::\n\n\nLastly, we plot a histogram of the *simulated values*, and overlay the *true distribution*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(beta_hat_2, prob = TRUE, breaks = 20, \n     xlab = expression(hat(beta)[2]), main = \"\", border = \"dodgerblue\")\ncurve(dnorm(x, mean = beta_2, sd = sqrt(sigma ^ 2 * C[2 + 1, 2 + 1])), \n      col = \"darkorange\", add = TRUE, lwd = 3)\n```\n\n::: {.cell-output-display}\n![](08_mlr_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThis looks good! The simulation-based histogram appears to be Normal with mean 6 and spread of about 0.15 as you measure from center to inflection point. That matches really well with the sampling distribution of $\\hat{\\beta}_2 \\sim N\\left(\\mu = 6, \\sigma^2 = 0.0232549  \\right)$.\n\nOne last check, we verify the $68 - 95 - 99.7$ rule.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsd_bh2 <- sqrt(sigma ^ 2 * C[2 + 1, 2 + 1])\n# We expect these to be: 0.68, 0.95, 0.997\nmean(beta_2 - 1 * sd_bh2 < beta_hat_2 & beta_hat_2 < beta_2 + 1 * sd_bh2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6807\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(beta_2 - 2 * sd_bh2 < beta_hat_2 & beta_hat_2 < beta_2 + 2 * sd_bh2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9529\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(beta_2 - 3 * sd_bh2 < beta_hat_2 & beta_hat_2 < beta_2 + 3 * sd_bh2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9967\n```\n\n\n:::\n:::\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}